#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    May 04, 2017 03:42:17 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import MoM_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = main_window (root)
    MoM_support.init(root, top)
    root.mainloop()

w = None
def create_main_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = main_window (w)
    MoM_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_main_window():
    global w
    w.destroy()
    w = None


class main_window:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1096x846+453+81")
        top.title("main_window")
        top.configure(background="#d9d9d9")



        self.save_button = Button(top)
        self.save_button.place(relx=0.32, rely=0.02, height=24, width=35)
        self.save_button.configure(activebackground="#d9d9d9")
        self.save_button.configure(activeforeground="#000000")
        self.save_button.configure(background="#d9d9d9")
        self.save_button.configure(disabledforeground="#a3a3a3")
        self.save_button.configure(foreground="#000000")
        self.save_button.configure(highlightbackground="#d9d9d9")
        self.save_button.configure(highlightcolor="black")
        self.save_button.configure(pady="0")
        self.save_button.configure(text='''Save''')

        self.attendees_text = Entry(top)
        self.attendees_text.place(relx=0.13, rely=0.02, relheight=0.02
                , relwidth=0.15)
        self.attendees_text.configure(background="white")
        self.attendees_text.configure(disabledforeground="#a3a3a3")
        self.attendees_text.configure(font="TkFixedFont")
        self.attendees_text.configure(foreground="#000000")
        self.attendees_text.configure(insertbackground="black")

        self.attendees_labe = Label(top)
        self.attendees_labe.place(relx=0.02, rely=0.02, height=21, width=62)
        self.attendees_labe.configure(background="#d9d9d9")
        self.attendees_labe.configure(disabledforeground="#a3a3a3")
        self.attendees_labe.configure(foreground="#000000")
        self.attendees_labe.configure(text='''Attendees:''')

        self.location_label = Label(top)
        self.location_label.place(relx=0.02, rely=0.06, height=21, width=68)
        self.location_label.configure(background="#d9d9d9")
        self.location_label.configure(disabledforeground="#a3a3a3")
        self.location_label.configure(foreground="#000000")
        self.location_label.configure(justify=RIGHT)
        self.location_label.configure(text='''Location:''')
        self.location_label.configure(width=68)

        self.location_text = Entry(top)
        self.location_text.place(relx=0.13, rely=0.06, relheight=0.02
                , relwidth=0.15)
        self.location_text.configure(background="white")
        self.location_text.configure(disabledforeground="#a3a3a3")
        self.location_text.configure(font="TkFixedFont")
        self.location_text.configure(foreground="#000000")
        self.location_text.configure(insertbackground="black")

        self.Label3 = Label(top)
        self.Label3.place(relx=0.02, rely=0.11, height=21, width=108)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Background/Topic:''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.where_to_save_label = Label(top)
        self.where_to_save_label.place(relx=0.61, rely=0.01, height=21, width=83)

        self.where_to_save_label.configure(background="#d9d9d9")
        self.where_to_save_label.configure(disabledforeground="#a3a3a3")
        self.where_to_save_label.configure(foreground="#000000")
        self.where_to_save_label.configure(text='''Where to save:''')

        self.where_to_save = ttk.Combobox(top)
        self.where_to_save.place(relx=0.69, rely=0.01, relheight=0.02
                , relwidth=0.13)
        self.where_to_save.configure(takefocus="")

        self.background_text = Text(top)
        self.background_text.place(relx=0.13, rely=0.11, relheight=0.12
                , relwidth=0.4)
        self.background_text.configure(background="white")
        self.background_text.configure(font="TkTextFont")
        self.background_text.configure(foreground="black")
        self.background_text.configure(highlightbackground="#d9d9d9")
        self.background_text.configure(highlightcolor="black")
        self.background_text.configure(insertbackground="black")
        self.background_text.configure(selectbackground="#c4c4c4")
        self.background_text.configure(selectforeground="black")
        self.background_text.configure(width=434)
        self.background_text.configure(wrap=WORD)

        self.Issue_label = Label(top)
        self.Issue_label.place(relx=0.02, rely=0.3, height=21, width=35)
        self.Issue_label.configure(background="#d9d9d9")
        self.Issue_label.configure(disabledforeground="#a3a3a3")
        self.Issue_label.configure(foreground="#000000")
        self.Issue_label.configure(text='''Issue:''')

        self.Issue_text_1 = Text(top)
        self.Issue_text_1.place(relx=0.03, rely=0.33, relheight=0.08
                , relwidth=0.3)
        self.Issue_text_1.configure(background="white")
        self.Issue_text_1.configure(font="TkTextFont")
        self.Issue_text_1.configure(foreground="black")
        self.Issue_text_1.configure(highlightbackground="#d9d9d9")
        self.Issue_text_1.configure(highlightcolor="black")
        self.Issue_text_1.configure(insertbackground="black")
        self.Issue_text_1.configure(selectbackground="#c4c4c4")
        self.Issue_text_1.configure(selectforeground="black")
        self.Issue_text_1.configure(width=324)
        self.Issue_text_1.configure(wrap=WORD)

        self.decision_label = Label(top)
        self.decision_label.place(relx=0.33, rely=0.3, height=21, width=54)
        self.decision_label.configure(background="#d9d9d9")
        self.decision_label.configure(disabledforeground="#a3a3a3")
        self.decision_label.configure(foreground="#000000")
        self.decision_label.configure(text='''Decision:''')

        self.decision_text_1 = Text(top)
        self.decision_text_1.place(relx=0.35, rely=0.33, relheight=0.08
                , relwidth=0.29)
        self.decision_text_1.configure(background="white")
        self.decision_text_1.configure(font="TkTextFont")
        self.decision_text_1.configure(foreground="black")
        self.decision_text_1.configure(highlightbackground="#d9d9d9")
        self.decision_text_1.configure(highlightcolor="black")
        self.decision_text_1.configure(insertbackground="black")
        self.decision_text_1.configure(selectbackground="#c4c4c4")
        self.decision_text_1.configure(selectforeground="black")
        self.decision_text_1.configure(width=314)
        self.decision_text_1.configure(wrap=WORD)

        self.TSizegrip1 = ttk.Sizegrip(top)
        self.TSizegrip1.place(anchor=SE, relx=1.0, rely=1.0)

        self.Assignee_label = Label(top)
        self.Assignee_label.place(relx=0.64, rely=0.3, height=21, width=56)
        self.Assignee_label.configure(background="#d9d9d9")
        self.Assignee_label.configure(disabledforeground="#a3a3a3")
        self.Assignee_label.configure(foreground="#000000")
        self.Assignee_label.configure(text='''Assignee:''')

        self.assignee_text_1 = Text(top)
        self.assignee_text_1.place(relx=0.66, rely=0.33, relheight=0.03
                , relwidth=0.14)
        self.assignee_text_1.configure(background="white")
        self.assignee_text_1.configure(font="TkTextFont")
        self.assignee_text_1.configure(foreground="black")
        self.assignee_text_1.configure(highlightbackground="#d9d9d9")
        self.assignee_text_1.configure(highlightcolor="black")
        self.assignee_text_1.configure(insertbackground="black")
        self.assignee_text_1.configure(selectbackground="#c4c4c4")
        self.assignee_text_1.configure(selectforeground="black")
        self.assignee_text_1.configure(width=154)
        self.assignee_text_1.configure(wrap=WORD)

        self.due_date_label = Label(top)
        self.due_date_label.place(relx=0.83, rely=0.3, height=21, width=57)
        self.due_date_label.configure(background="#d9d9d9")
        self.due_date_label.configure(disabledforeground="#a3a3a3")
        self.due_date_label.configure(foreground="#000000")
        self.due_date_label.configure(text='''Due Date:''')

        self.due_date_text_1 = Text(top)
        self.due_date_text_1.place(relx=0.83, rely=0.33, relheight=0.03
                , relwidth=0.12)
        self.due_date_text_1.configure(background="white")
        self.due_date_text_1.configure(font="TkTextFont")
        self.due_date_text_1.configure(foreground="black")
        self.due_date_text_1.configure(highlightbackground="#d9d9d9")
        self.due_date_text_1.configure(highlightcolor="black")
        self.due_date_text_1.configure(insertbackground="black")
        self.due_date_text_1.configure(selectbackground="#c4c4c4")
        self.due_date_text_1.configure(selectforeground="black")
        self.due_date_text_1.configure(width=134)
        self.due_date_text_1.configure(wrap=WORD)

        self.Issue_text_2 = Text(top)
        self.Issue_text_2.place(relx=0.03, rely=0.46, relheight=0.08
                , relwidth=0.3)
        self.Issue_text_2.configure(background="white")
        self.Issue_text_2.configure(font="TkTextFont")
        self.Issue_text_2.configure(foreground="black")
        self.Issue_text_2.configure(highlightbackground="#d9d9d9")
        self.Issue_text_2.configure(highlightcolor="black")
        self.Issue_text_2.configure(insertbackground="black")
        self.Issue_text_2.configure(selectbackground="#c4c4c4")
        self.Issue_text_2.configure(selectforeground="black")
        self.Issue_text_2.configure(width=324)
        self.Issue_text_2.configure(wrap=WORD)

        self.decision_text_2 = Text(top)
        self.decision_text_2.place(relx=0.35, rely=0.46, relheight=0.08
                , relwidth=0.29)
        self.decision_text_2.configure(background="white")
        self.decision_text_2.configure(font="TkTextFont")
        self.decision_text_2.configure(foreground="black")
        self.decision_text_2.configure(highlightbackground="#d9d9d9")
        self.decision_text_2.configure(highlightcolor="black")
        self.decision_text_2.configure(insertbackground="black")
        self.decision_text_2.configure(selectbackground="#c4c4c4")
        self.decision_text_2.configure(selectforeground="black")
        self.decision_text_2.configure(width=314)
        self.decision_text_2.configure(wrap=WORD)

        self.assignee_text_2 = Text(top)
        self.assignee_text_2.place(relx=0.67, rely=0.46, relheight=0.03
                , relwidth=0.14)
        self.assignee_text_2.configure(background="white")
        self.assignee_text_2.configure(font="TkTextFont")
        self.assignee_text_2.configure(foreground="black")
        self.assignee_text_2.configure(highlightbackground="#d9d9d9")
        self.assignee_text_2.configure(highlightcolor="black")
        self.assignee_text_2.configure(insertbackground="black")
        self.assignee_text_2.configure(selectbackground="#c4c4c4")
        self.assignee_text_2.configure(selectforeground="black")
        self.assignee_text_2.configure(width=154)
        self.assignee_text_2.configure(wrap=WORD)

        self.due_date_text_2 = Text(top)
        self.due_date_text_2.place(relx=0.83, rely=0.46, relheight=0.03
                , relwidth=0.12)
        self.due_date_text_2.configure(background="white")
        self.due_date_text_2.configure(font="TkTextFont")
        self.due_date_text_2.configure(foreground="black")
        self.due_date_text_2.configure(highlightbackground="#d9d9d9")
        self.due_date_text_2.configure(highlightcolor="black")
        self.due_date_text_2.configure(insertbackground="black")
        self.due_date_text_2.configure(selectbackground="#c4c4c4")
        self.due_date_text_2.configure(selectforeground="black")
        self.due_date_text_2.configure(width=134)
        self.due_date_text_2.configure(wrap=WORD)

        self.Issue_text_3 = Text(top)
        self.Issue_text_3.place(relx=0.03, rely=0.59, relheight=0.08
                , relwidth=0.3)
        self.Issue_text_3.configure(background="white")
        self.Issue_text_3.configure(font="TkTextFont")
        self.Issue_text_3.configure(foreground="black")
        self.Issue_text_3.configure(highlightbackground="#d9d9d9")
        self.Issue_text_3.configure(highlightcolor="black")
        self.Issue_text_3.configure(insertbackground="black")
        self.Issue_text_3.configure(selectbackground="#c4c4c4")
        self.Issue_text_3.configure(selectforeground="black")
        self.Issue_text_3.configure(width=324)
        self.Issue_text_3.configure(wrap=WORD)

        self.decision_text_3 = Text(top)
        self.decision_text_3.place(relx=0.35, rely=0.59, relheight=0.08
                , relwidth=0.29)
        self.decision_text_3.configure(background="white")
        self.decision_text_3.configure(font="TkTextFont")
        self.decision_text_3.configure(foreground="black")
        self.decision_text_3.configure(highlightbackground="#d9d9d9")
        self.decision_text_3.configure(highlightcolor="black")
        self.decision_text_3.configure(insertbackground="black")
        self.decision_text_3.configure(selectbackground="#c4c4c4")
        self.decision_text_3.configure(selectforeground="black")
        self.decision_text_3.configure(width=314)
        self.decision_text_3.configure(wrap=WORD)

        self.assignee_text_3 = Text(top)
        self.assignee_text_3.place(relx=0.66, rely=0.59, relheight=0.03
                , relwidth=0.14)
        self.assignee_text_3.configure(background="white")
        self.assignee_text_3.configure(font="TkTextFont")
        self.assignee_text_3.configure(foreground="black")
        self.assignee_text_3.configure(highlightbackground="#d9d9d9")
        self.assignee_text_3.configure(highlightcolor="black")
        self.assignee_text_3.configure(insertbackground="black")
        self.assignee_text_3.configure(selectbackground="#c4c4c4")
        self.assignee_text_3.configure(selectforeground="black")
        self.assignee_text_3.configure(width=154)
        self.assignee_text_3.configure(wrap=WORD)

        self.due_date_text_3 = Text(top)
        self.due_date_text_3.place(relx=0.84, rely=0.59, relheight=0.03
                , relwidth=0.12)
        self.due_date_text_3.configure(background="white")
        self.due_date_text_3.configure(font="TkTextFont")
        self.due_date_text_3.configure(foreground="black")
        self.due_date_text_3.configure(highlightbackground="#d9d9d9")
        self.due_date_text_3.configure(highlightcolor="black")
        self.due_date_text_3.configure(insertbackground="black")
        self.due_date_text_3.configure(selectbackground="#c4c4c4")
        self.due_date_text_3.configure(selectforeground="black")
        self.due_date_text_3.configure(width=134)
        self.due_date_text_3.configure(wrap=WORD)

        self.Issue_text_4 = Text(top)
        self.Issue_text_4.place(relx=0.03, rely=0.71, relheight=0.08
                , relwidth=0.3)
        self.Issue_text_4.configure(background="white")
        self.Issue_text_4.configure(font="TkTextFont")
        self.Issue_text_4.configure(foreground="black")
        self.Issue_text_4.configure(highlightbackground="#d9d9d9")
        self.Issue_text_4.configure(highlightcolor="black")
        self.Issue_text_4.configure(insertbackground="black")
        self.Issue_text_4.configure(selectbackground="#c4c4c4")
        self.Issue_text_4.configure(selectforeground="black")
        self.Issue_text_4.configure(width=324)
        self.Issue_text_4.configure(wrap=WORD)

        self.decision_text_4 = Text(top)
        self.decision_text_4.place(relx=0.35, rely=0.71, relheight=0.08
                , relwidth=0.29)
        self.decision_text_4.configure(background="white")
        self.decision_text_4.configure(font="TkTextFont")
        self.decision_text_4.configure(foreground="black")
        self.decision_text_4.configure(highlightbackground="#d9d9d9")
        self.decision_text_4.configure(highlightcolor="black")
        self.decision_text_4.configure(insertbackground="black")
        self.decision_text_4.configure(selectbackground="#c4c4c4")
        self.decision_text_4.configure(selectforeground="black")
        self.decision_text_4.configure(width=314)
        self.decision_text_4.configure(wrap=WORD)

        self.assignee_text_4 = Text(top)
        self.assignee_text_4.place(relx=0.66, rely=0.71, relheight=0.03
                , relwidth=0.14)
        self.assignee_text_4.configure(background="white")
        self.assignee_text_4.configure(cursor="fleur")
        self.assignee_text_4.configure(font="TkTextFont")
        self.assignee_text_4.configure(foreground="black")
        self.assignee_text_4.configure(highlightbackground="#d9d9d9")
        self.assignee_text_4.configure(highlightcolor="black")
        self.assignee_text_4.configure(insertbackground="black")
        self.assignee_text_4.configure(selectbackground="#c4c4c4")
        self.assignee_text_4.configure(selectforeground="black")
        self.assignee_text_4.configure(width=154)
        self.assignee_text_4.configure(wrap=WORD)

        self.due_date_text_4 = Text(top)
        self.due_date_text_4.place(relx=0.83, rely=0.71, relheight=0.03
                , relwidth=0.12)
        self.due_date_text_4.configure(background="white")
        self.due_date_text_4.configure(font="TkTextFont")
        self.due_date_text_4.configure(foreground="black")
        self.due_date_text_4.configure(highlightbackground="#d9d9d9")
        self.due_date_text_4.configure(highlightcolor="black")
        self.due_date_text_4.configure(insertbackground="black")
        self.due_date_text_4.configure(selectbackground="#c4c4c4")
        self.due_date_text_4.configure(selectforeground="black")
        self.due_date_text_4.configure(width=134)
        self.due_date_text_4.configure(wrap=WORD)

        self.Issue_text_5 = Text(top)
        self.Issue_text_5.place(relx=0.03, rely=0.83, relheight=0.08
                , relwidth=0.3)
        self.Issue_text_5.configure(background="white")
        self.Issue_text_5.configure(font="TkTextFont")
        self.Issue_text_5.configure(foreground="black")
        self.Issue_text_5.configure(highlightbackground="#d9d9d9")
        self.Issue_text_5.configure(highlightcolor="black")
        self.Issue_text_5.configure(insertbackground="black")
        self.Issue_text_5.configure(selectbackground="#c4c4c4")
        self.Issue_text_5.configure(selectforeground="black")
        self.Issue_text_5.configure(width=324)
        self.Issue_text_5.configure(wrap=WORD)

        self.decision_text_5 = Text(top)
        self.decision_text_5.place(relx=0.35, rely=0.83, relheight=0.08
                , relwidth=0.29)
        self.decision_text_5.configure(background="white")
        self.decision_text_5.configure(font="TkTextFont")
        self.decision_text_5.configure(foreground="black")
        self.decision_text_5.configure(highlightbackground="#d9d9d9")
        self.decision_text_5.configure(highlightcolor="black")
        self.decision_text_5.configure(insertbackground="black")
        self.decision_text_5.configure(selectbackground="#c4c4c4")
        self.decision_text_5.configure(selectforeground="black")
        self.decision_text_5.configure(width=314)
        self.decision_text_5.configure(wrap=WORD)

        self.assignee_text_5 = Text(top)
        self.assignee_text_5.place(relx=0.66, rely=0.83, relheight=0.03
                , relwidth=0.14)
        self.assignee_text_5.configure(background="white")
        self.assignee_text_5.configure(font="TkTextFont")
        self.assignee_text_5.configure(foreground="black")
        self.assignee_text_5.configure(highlightbackground="#d9d9d9")
        self.assignee_text_5.configure(highlightcolor="black")
        self.assignee_text_5.configure(insertbackground="black")
        self.assignee_text_5.configure(selectbackground="#c4c4c4")
        self.assignee_text_5.configure(selectforeground="black")
        self.assignee_text_5.configure(width=154)
        self.assignee_text_5.configure(wrap=WORD)

        self.due_date_text_5 = Text(top)
        self.due_date_text_5.place(relx=0.83, rely=0.83, relheight=0.03
                , relwidth=0.12)
        self.due_date_text_5.configure(background="white")
        self.due_date_text_5.configure(cursor="fleur")
        self.due_date_text_5.configure(font="TkTextFont")
        self.due_date_text_5.configure(foreground="black")
        self.due_date_text_5.configure(highlightbackground="#d9d9d9")
        self.due_date_text_5.configure(highlightcolor="black")
        self.due_date_text_5.configure(insertbackground="black")
        self.due_date_text_5.configure(selectbackground="#c4c4c4")
        self.due_date_text_5.configure(selectforeground="black")
        self.due_date_text_5.configure(width=134)
        self.due_date_text_5.configure(wrap=WORD)






if __name__ == '__main__':
    vp_start_gui()


