#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 1096x846+453+81
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3828 1045
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "main_window"
    vTcl:DefineAlias "$top" "main_window" vTcl:Toplevel:WidgetProc "" 1
    button $top.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Save 
    vTcl:DefineAlias "$top.but38" "save_button" vTcl:WidgetProc "main_window" 1
    entry $top.ent39 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent39" "attendees" vTcl:WidgetProc "main_window" 1
    label $top.lab40 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Attendees: 
    vTcl:DefineAlias "$top.lab40" "attendees_labe" vTcl:WidgetProc "main_window" 1
    label $top.lab41 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -justify right -text {Location: } 
    vTcl:DefineAlias "$top.lab41" "location_label" vTcl:WidgetProc "main_window" 1
    entry $top.ent42 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent42" "location" vTcl:WidgetProc "main_window" 1
    label $top.lab43 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Background/Topic: 
    vTcl:DefineAlias "$top.lab43" "Label3" vTcl:WidgetProc "main_window" 1
    menu $top.m51 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.lab53 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Where to save:} 
    vTcl:DefineAlias "$top.lab53" "where_to_save_label" vTcl:WidgetProc "main_window" 1
    ttk::combobox $top.tCo56 \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo56" "where_to_save" vTcl:WidgetProc "main_window" 1
    text $top.tex59 \
        -background white -font TkTextFont -foreground black -height 104 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 434 -wrap word 
    .top37.tex59 configure -font TkTextFont
    .top37.tex59 insert end text
    vTcl:DefineAlias "$top.tex59" "background" vTcl:WidgetProc "main_window" 1
    label $top.lab61 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Issue: 
    vTcl:DefineAlias "$top.lab61" "Issue_label" vTcl:WidgetProc "main_window" 1
    text $top.tex62 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 324 -wrap word 
    .top37.tex62 configure -font TkTextFont
    .top37.tex62 insert end text
    vTcl:DefineAlias "$top.tex62" "Issue_text_1" vTcl:WidgetProc "main_window" 1
    label $top.lab63 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Decision: 
    vTcl:DefineAlias "$top.lab63" "decision_label" vTcl:WidgetProc "main_window" 1
    text $top.tex64 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top37.tex64 configure -font TkTextFont
    .top37.tex64 insert end text
    vTcl:DefineAlias "$top.tex64" "decision_text_1" vTcl:WidgetProc "main_window" 1
    ttk::style configure TSizegrip -background #d9d9d9
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.cpd65 \
        -cursor bottom_left_corner 
    vTcl:DefineAlias "$top.cpd65" "TSizegrip1" vTcl:WidgetProc "main_window" 1
    label $top.lab66 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Assignee: 
    vTcl:DefineAlias "$top.lab66" "Assignee_label" vTcl:WidgetProc "main_window" 1
    text $top.tex67 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 154 -wrap word 
    .top37.tex67 configure -font TkTextFont
    .top37.tex67 insert end text
    vTcl:DefineAlias "$top.tex67" "Text4" vTcl:WidgetProc "main_window" 1
    label $top.lab68 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Due Date:} 
    vTcl:DefineAlias "$top.lab68" "due_date_label" vTcl:WidgetProc "main_window" 1
    text $top.tex69 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 134 -wrap word 
    .top37.tex69 configure -font TkTextFont
    .top37.tex69 insert end text
    vTcl:DefineAlias "$top.tex69" "Text5" vTcl:WidgetProc "main_window" 1
    text $top.cpd70 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 324 -wrap word 
    .top37.cpd70 configure -font TkTextFont
    .top37.cpd70 insert end text
    vTcl:DefineAlias "$top.cpd70" "Issue_text_2" vTcl:WidgetProc "main_window" 1
    text $top.cpd71 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top37.cpd71 configure -font TkTextFont
    .top37.cpd71 insert end text
    vTcl:DefineAlias "$top.cpd71" "decision_text_2" vTcl:WidgetProc "main_window" 1
    text $top.cpd72 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 154 -wrap word 
    .top37.cpd72 configure -font TkTextFont
    .top37.cpd72 insert end text
    vTcl:DefineAlias "$top.cpd72" "Text6" vTcl:WidgetProc "main_window" 1
    text $top.cpd73 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 134 -wrap word 
    .top37.cpd73 configure -font TkTextFont
    .top37.cpd73 insert end text
    vTcl:DefineAlias "$top.cpd73" "Text7" vTcl:WidgetProc "main_window" 1
    text $top.cpd74 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 324 -wrap word 
    .top37.cpd74 configure -font TkTextFont
    .top37.cpd74 insert end text
    vTcl:DefineAlias "$top.cpd74" "Issue_text_3" vTcl:WidgetProc "main_window" 1
    text $top.cpd75 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top37.cpd75 configure -font TkTextFont
    .top37.cpd75 insert end text
    vTcl:DefineAlias "$top.cpd75" "decision_text_3" vTcl:WidgetProc "main_window" 1
    text $top.cpd76 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 154 -wrap word 
    .top37.cpd76 configure -font TkTextFont
    .top37.cpd76 insert end text
    vTcl:DefineAlias "$top.cpd76" "Text8" vTcl:WidgetProc "main_window" 1
    text $top.cpd77 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 134 -wrap word 
    .top37.cpd77 configure -font TkTextFont
    .top37.cpd77 insert end text
    vTcl:DefineAlias "$top.cpd77" "Text9" vTcl:WidgetProc "main_window" 1
    text $top.cpd78 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 324 -wrap word 
    .top37.cpd78 configure -font TkTextFont
    .top37.cpd78 insert end text
    vTcl:DefineAlias "$top.cpd78" "Issue_text_4" vTcl:WidgetProc "main_window" 1
    text $top.cpd79 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top37.cpd79 configure -font TkTextFont
    .top37.cpd79 insert end text
    vTcl:DefineAlias "$top.cpd79" "decision_text_4" vTcl:WidgetProc "main_window" 1
    text $top.cpd80 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 154 -wrap word 
    .top37.cpd80 configure -font TkTextFont
    .top37.cpd80 insert end text
    vTcl:DefineAlias "$top.cpd80" "Text10" vTcl:WidgetProc "main_window" 1
    text $top.cpd81 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 134 -wrap word 
    .top37.cpd81 configure -font TkTextFont
    .top37.cpd81 insert end text
    vTcl:DefineAlias "$top.cpd81" "Text11" vTcl:WidgetProc "main_window" 1
    text $top.cpd85 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 324 -wrap word 
    .top37.cpd85 configure -font TkTextFont
    .top37.cpd85 insert end text
    vTcl:DefineAlias "$top.cpd85" "Issue_text_5" vTcl:WidgetProc "main_window" 1
    text $top.cpd86 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 314 -wrap word 
    .top37.cpd86 configure -font TkTextFont
    .top37.cpd86 insert end text
    vTcl:DefineAlias "$top.cpd86" "decision_text_5" vTcl:WidgetProc "main_window" 1
    text $top.cpd87 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 154 -wrap word 
    .top37.cpd87 configure -font TkTextFont
    .top37.cpd87 insert end text
    vTcl:DefineAlias "$top.cpd87" "Text12" vTcl:WidgetProc "main_window" 1
    text $top.cpd88 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 134 -wrap word 
    .top37.cpd88 configure -font TkTextFont
    .top37.cpd88 insert end text
    vTcl:DefineAlias "$top.cpd88" "Text13" vTcl:WidgetProc "main_window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but38 \
        -in $top -x 350 -y 20 -anchor nw -bordermode ignore 
    place $top.ent39 \
        -in $top -x 140 -y 20 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 20 -y 20 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 20 -y 50 -width 68 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent42 \
        -in $top -x 140 -y 50 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 20 -y 90 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 670 -y 10 -anchor nw -bordermode ignore 
    place $top.tCo56 \
        -in $top -x 760 -y 10 -anchor nw -bordermode ignore 
    place $top.tex59 \
        -in $top -x 140 -y 90 -width 434 -relwidth 0 -height 104 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 20 -y 250 -anchor nw -bordermode ignore 
    place $top.tex62 \
        -in $top -x 30 -y 280 -width 324 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 360 -y 250 -anchor nw -bordermode ignore 
    place $top.tex64 \
        -in $top -x 380 -y 280 -width 314 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd65 \
        -in $top -x 1080 -y 830 -width 16 -height 16 -anchor nw \
        -bordermode inside 
    place $top.lab66 \
        -in $top -x 700 -y 250 -anchor nw -bordermode ignore 
    place $top.tex67 \
        -in $top -x 720 -y 280 -width 154 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 910 -y 250 -anchor nw -bordermode ignore 
    place $top.tex69 \
        -in $top -x 910 -y 280 -width 134 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd70 \
        -in $top -x 30 -y 390 -width 324 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd71 \
        -in $top -x 380 -y 390 -width 314 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd72 \
        -in $top -x 720 -y 390 -width 154 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd73 \
        -in $top -x 910 -y 390 -width 134 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd74 \
        -in $top -x 30 -y 500 -width 324 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd75 \
        -in $top -x 380 -y 500 -width 314 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd76 \
        -in $top -x 720 -y 500 -width 154 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd77 \
        -in $top -x 910 -y 500 -width 134 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd78 \
        -in $top -x 30 -y 600 -width 324 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd79 \
        -in $top -x 380 -y 600 -width 314 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd80 \
        -in $top -x 720 -y 600 -width 154 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd81 \
        -in $top -x 910 -y 600 -width 134 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd85 \
        -in $top -x 30 -y 700 -width 324 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd86 \
        -in $top -x 380 -y 700 -width 314 -height 64 -anchor nw \
        -bordermode inside 
    place $top.cpd87 \
        -in $top -x 720 -y 700 -width 154 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd88 \
        -in $top -x 910 -y 700 -width 134 -height 24 -anchor nw \
        -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

